### ISSUE TITLE
Tests for `clock` conversion fail

### ISSUE THREAD

**Issue by etiennebacher** [pola-rs/r-polars#875] opened 2024-03-01 12:09 UTC
The tests for `clock` added in #861 do not work for me locally. Here are some examples of failures (I only include `precision = "day"` and values for naive time but it fails for all precisions and for all type of time):

```r
> precision = "day"
> naive_time_chr = c(
  "1900-01-01T12:34:56.123456789",
  "2012-01-01T12:34:56.123456789",
  "2212-01-01T12:34:56.123456789"
)

### Results for clock
> clock_naive_time = clock::naive_time_parse(naive_time_chr, precision = precision)
> clock_naive_time
<naive_time<day>[3]>
[1] "1900-01-01" "2012-01-01" "2212-01-01"
> as.POSIXct(clock_naive_time)
[1] "1900-01-01 PMT" "2012-01-01 CET" "2212-01-01 CET"

### Results for polars
> pl_naive_time = as_polars_series(clock_naive_time)
> pl_naive_time
polars Series: shape: (3,)
Series: '' [datetime[ms]]
[
	1900-01-01 00:00:00
	2012-01-01 00:00:00
	2212-01-01 00:00:00
]
> as.POSIXct(as.vector(pl_naive_time))
[1] "1900-01-01 00:09:21 PMT" "2012-01-01 01:00:00 CET" "2212-01-01 01:00:00 CET"
```

**Comment by eitsupi** [comment] 2024-03-01 12:25
Thanks for finding this. Perhaps the timezone is overridden by calling `as.POSIXct`.

How about `as.POSIXct(clock_naive_time) == as.vector(pl_naive_time)`?

**Comment by eitsupi** [comment] 2024-03-01 12:32
Curious.
What is the output of `sessioninfo::session_info()`?

**Comment by etiennebacher** [comment] 2024-03-01 12:33
```r
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.3 (2024-02-29 ucrt)
 os       Windows 10 x64 (build 19044)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_Europe.utf8
 ctype    English_Europe.utf8
 tz       Europe/Paris
 date     2024-03-01
 rstudio  2023.06.2+561 Mountain Hydrangea (desktop)
 pandoc   3.1.1 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 !  package     * version     date (UTC) lib source
    arrow       * 14.0.0.2    2023-12-02 [1] CRAN (R 4.3.2)
    askpass       1.2.0       2023-09-03 [1] CRAN (R 4.3.1)
    assertthat    0.2.1       2019-03-21 [1] CRAN (R 4.3.0)
    bench         1.1.3       2023-05-04 [1] CRAN (R 4.3.0)
    bit           4.0.5       2022-11-15 [1] CRAN (R 4.3.0)
    bit64         4.0.5       2020-08-30 [1] CRAN (R 4.3.0)
    brio          1.1.4       2023-12-10 [1] CRAN (R 4.3.2)
    cachem        1.0.8       2023-05-01 [1] CRAN (R 4.3.0)
    callr         3.7.5       2024-02-19 [1] CRAN (R 4.3.2)
    cli           3.6.2       2023-12-11 [1] CRAN (R 4.3.2)
    clipr         0.8.0       2022-02-22 [1] CRAN (R 4.3.0)
    clock         0.7.0       2023-05-15 [1] CRAN (R 4.3.0)
    codetools     0.2-19      2023-02-01 [1] CRAN (R 4.3.3)
    crayon        1.5.2       2022-09-29 [1] CRAN (R 4.3.0)
    credentials   2.0.1       2023-09-06 [1] CRAN (R 4.3.1)
    curl          5.2.0       2023-12-08 [1] CRAN (R 4.3.2)
    desc          1.4.3       2023-12-10 [1] CRAN (R 4.3.2)
    devtools      2.4.5       2022-10-11 [1] CRAN (R 4.3.0)
    digest        0.6.34      2024-01-11 [1] CRAN (R 4.3.2)
    dplyr       * 1.1.4       2023-11-17 [1] CRAN (R 4.3.2)
    ellipsis      0.3.2       2021-04-29 [1] CRAN (R 4.3.0)
    evaluate      0.23        2023-11-01 [1] CRAN (R 4.3.2)
    fansi         1.0.6       2023-12-08 [1] CRAN (R 4.3.2)
    fastmap       1.1.1       2023-02-24 [1] CRAN (R 4.3.0)
    fs            1.6.3       2023-07-20 [1] CRAN (R 4.3.1)
    generics      0.1.3       2022-07-05 [1] CRAN (R 4.3.0)
    gert          2.0.1       2023-12-04 [1] CRAN (R 4.3.2)
    gh            1.4.0       2023-02-22 [1] CRAN (R 4.3.0)
    gitcreds      0.1.2       2022-09-08 [1] CRAN (R 4.3.0)
    glue          1.7.0       2024-01-09 [1] CRAN (R 4.3.2)
    htmltools     0.5.7       2023-11-03 [1] CRAN (R 4.3.2)
    htmlwidgets   1.6.4       2023-12-06 [1] CRAN (R 4.3.2)
    httpuv        1.6.14      2024-01-26 [1] CRAN (R 4.3.2)
    httr2         1.0.0       2023-11-14 [1] CRAN (R 4.3.2)
    jsonlite      1.8.8       2023-12-04 [1] CRAN (R 4.3.2)
    knitr       * 1.45        2023-10-30 [1] CRAN (R 4.3.1)
    later         1.3.2       2023-12-06 [1] CRAN (R 4.3.2)
    lifecycle     1.0.4       2023-11-07 [1] CRAN (R 4.3.2)
    magrittr      2.0.3       2022-03-30 [1] CRAN (R 4.3.0)
    memoise       2.0.1       2021-11-26 [1] CRAN (R 4.3.0)
    mime          0.12        2021-09-28 [1] CRAN (R 4.3.0)
    miniUI        0.1.1.1     2018-05-18 [1] CRAN (R 4.3.0)
    nanoarrow   * 0.4.0.1     2024-02-23 [1] CRAN (R 4.3.2)
    openssl       2.1.1       2023-09-25 [1] CRAN (R 4.3.1)
    patrick       0.2.0       2022-10-13 [1] CRAN (R 4.3.0)
    pillar        1.9.0       2023-03-22 [1] CRAN (R 4.3.0)
    pkgbuild      1.4.3       2023-12-10 [1] CRAN (R 4.3.2)
    pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.3.0)
    pkgload       1.3.4       2024-01-16 [1] CRAN (R 4.3.2)
 VP polars      * 0.14.1.9000 2024-02-23 [?] https://rpolars.r-universe.dev (R 4.3.2) (on disk 0.14.1)
    processx      3.8.3       2023-12-10 [1] CRAN (R 4.3.2)
    profmem       0.6.0       2020-12-13 [1] CRAN (R 4.3.0)
    profvis       0.3.8       2023-05-02 [1] CRAN (R 4.3.0)
    promises      1.2.1       2023-08-10 [1] CRAN (R 4.3.1)
    ps            1.7.6       2024-01-18 [1] CRAN (R 4.3.2)
    purrr         1.0.2       2023-08-10 [1] CRAN (R 4.3.1)
    R.cache       0.16.0      2022-07-21 [1] CRAN (R 4.3.0)
    R.methodsS3   1.8.2       2022-06-13 [1] CRAN (R 4.3.0)
    R.oo          1.26.0      2024-01-24 [1] CRAN (R 4.3.2)
    R.utils       2.12.3      2023-11-18 [1] CRAN (R 4.3.2)
    R6            2.5.1       2021-08-19 [1] CRAN (R 4.3.0)
    rappdirs      0.3.3       2021-01-31 [1] CRAN (R 4.3.0)
    Rcpp          1.0.12      2024-01-09 [1] CRAN (R 4.3.2)
    remotes       2.4.2.1     2023-07-18 [1] CRAN (R 4.3.1)
    reprex        2.1.0.9000  2024-01-12 [1] Github (tidyverse/reprex@33ccedf)
    rlang         1.1.3       2024-01-10 [1] CRAN (R 4.3.2)
    rmarkdown     2.25.3      2024-02-07 [1] Github (rstudio/rmarkdown@07e2a99)
    rprojroot     2.0.4       2023-11-05 [1] CRAN (R 4.3.1)
    rstudioapi    0.15.0      2023-07-07 [1] CRAN (R 4.3.1)
    sessioninfo   1.2.2       2021-12-06 [1] CRAN (R 4.3.0)
    shiny         1.8.0       2023-11-17 [1] CRAN (R 4.3.2)
    stringi       1.8.3       2023-12-11 [1] CRAN (R 4.3.2)
    stringr       1.5.1       2023-11-14 [1] CRAN (R 4.3.2)
    styler        1.10.2      2023-08-29 [1] CRAN (R 4.3.1)
    sys           3.4.2       2023-05-23 [1] CRAN (R 4.3.0)
    testthat    * 3.2.1       2023-12-02 [1] CRAN (R 4.3.2)
    tibble        3.2.1       2023-03-20 [1] CRAN (R 4.3.0)
    tidyselect    1.2.0       2022-10-10 [1] CRAN (R 4.3.0)
    tzdb          0.4.0       2023-05-12 [1] CRAN (R 4.3.0)
    urlchecker    1.0.1       2021-11-30 [1] CRAN (R 4.3.0)
    usethis       2.2.3       2024-02-19 [1] CRAN (R 4.3.2)
    utf8          1.2.4       2023-10-22 [1] CRAN (R 4.3.2)
    vctrs         0.6.5.9000  2023-12-14 [1] Github (r-lib/vctrs@8bf5ba5)
    withr         3.0.0       2024-01-16 [1] CRAN (R 4.3.2)
    xfun          0.42        2024-02-08 [1] CRAN (R 4.3.2)
    xtable        1.8-4       2019-04-21 [1] CRAN (R 4.3.0)
    yaml          2.3.8       2023-12-11 [1] CRAN (R 4.3.2)

 [1] C:/Users/etienne/AppData/Local/Programs/R/R-4.3.3/library

 V ── Loaded and on-disk version mismatch.
 P ── Loaded and on-disk path mismatch.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by eitsupi** [comment] 2024-03-01 12:42
Ah, I think I understand, there seems to be an added assumption that the timezone is UTC when converting from Polars to R.

**Comment by etiennebacher** [comment] 2024-03-01 12:43
Could be, but then maybe there's a bug upstream:

```r
naive_time_chr = c("1901-01-01", "1911-01-01", "1921-01-01")
naive_time_chr |> 
  clock::naive_time_parse(precision = "day") |> 
  as_polars_series() |> 
  as.vector()

[1] "1901-01-01 00:09:21 PMT" "1911-01-01 00:09:21 PMT" "1921-01-01 00:00:00 WET"
```

**Comment by eitsupi** [comment] 2024-03-01 12:47
Yes, the 9-minute discrepancy could be another issue.
I reproduce it on my Linux, so this must be a behavior specific to this time zone.

```r
> Sys.setenv(TZ="Europe/Paris")

> naive_time_chr = c("1901-01-01", "1911-01-01", "1921-01-01")
> naive_time_chr |> 
      clock::naive_time_parse(precision = "day") |> 
      as_polars_series() |> 
      as.vector()
[1] "1901-01-01 00:09:21 PMT" "1911-01-01 00:09:21 PMT" "1921-01-01 00:00:00 WET"
```

I am not familiar with this time zone, so I don't know much about it, but is it possible that it was off by 9 minutes 100 years ago?

**Comment by etiennebacher** [comment] 2024-03-01 12:50
> is it possible that it was off by 9 minutes 100 years ago?

That's what make me hate datetime handling 😄 

But even then, why does the timezone matter if we use `precision = "day"`?

**Comment by eitsupi** [comment] 2024-03-01 12:54
> But even then, why does the timezone matter if we use `precision = "day"`?

Unlike clock, the datetime type of Polars has units of ms, us, or ns, and I think the time is off because the conversion to the POSIXct type has taken the time zone into account.

**Comment by etiennebacher** [comment] 2024-03-01 12:55
Alright, I don't know how to fix this so I'll let you handle it

**Comment by eitsupi** [comment] 2024-03-01 13:23
Can you change the time zone to UTC as a workaround for now?

**Comment by eitsupi** [comment] 2024-03-01 13:42
Hmmm apparently this is not a bug of Polars.......

``` r
Sys.setenv(TZ = "UTC")
x = "1900-01-01"
s = polars::as_polars_series(x)$str$strptime(pl$Datetime(), "%F")

s
#> polars Series: shape: (1,)
#> Series: '' [datetime[μs]]
#> [
#>  1900-01-01 00:00:00
#> ]
s$to_r()
#> [1] "1900-01-01 UTC"
s$to_r() |> unclass()
#> [1] -2208988800
#> attr(,"tzone")
#> [1] ""

Sys.setenv(TZ = "Europe/Paris")

s
#> polars Series: shape: (1,)
#> Series: '' [datetime[μs]]
#> [
#>  1900-01-01 00:00:00
#> ]
s$to_r()
#> [1] "1900-01-01 00:09:21 PMT"
s$to_r() |> unclass()
#> [1] -2208988800
#> attr(,"tzone")
#> [1] ""
```

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
~

**Comment by eitsupi** [comment] 2024-03-01 13:47
<https://en.wikipedia.org/wiki/Time_in_France> says:

> Before 1891, each town and city in [Metropolitan France](https://en.wikipedia.org/wiki/Metropolitan_France) had its own time based on local [solar time](https://en.wikipedia.org/wiki/Solar_time). In 1891, to avoid complications with railway timetables, time was unified in Metropolitan France and based on the solar time at the [Paris Observatory](https://en.wikipedia.org/wiki/Paris_Observatory) — the [Paris meridian](https://en.wikipedia.org/wiki/Paris_meridian) being approximately 2°20′ east of the [Greenwich meridian](https://en.wikipedia.org/wiki/Greenwich_meridian), Paris mean solar time was 9 minutes 21 seconds ahead of [Greenwich Mean Time](https://en.wikipedia.org/wiki/Greenwich_Mean_Time) (GMT). In detail, the railway companies used a unified time which lagged behind Paris solar time by 5 minutes, for the benefit of non-punctual travellers.[[5]](https://en.wikipedia.org/wiki/Time_in_France#cite_note-5) In 1911, Metropolitan France adopted GMT+0 as its official time, and used it until 1940 (with GMT+1 used during the summers from 1916 to 1940).

Time zones are truly frightening.......

**Comment by eitsupi** [comment] 2024-03-01 14:16
The Arrow package seems to handle timestamps without time zone in the same way.

``` r
Sys.setenv(TZ = "UTC")
x = "1900-01-01"
df = polars::as_polars_series(x)$str$strptime(pl$Datetime(), "%F")$to_frame()

df |> arrow::as_arrow_table() |> as.data.frame()
#>
#> 1 1900-01-01

Sys.setenv(TZ = "Europe/Paris")
df |> arrow::as_arrow_table() |> as.data.frame()
#>
#> 1 1900-01-01 00:09:21
```

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

To me this is pretty amazing behavior and should be fixed, but it means that the value returned will change depending on the time zone the user is in. (i.e. now the display is different but the internal values are the same)
Should this behavior be fixed?

**Comment by eitsupi** [comment] 2024-03-01 14:34
``` r
library(arrow)
#>
#> Attaching package: 'arrow'
#> The following object is masked from 'package:utils':
#>
#>     timestamp

Sys.setenv(TZ = "UTC")

x <- "1900-01-01"
a_a <- chunked_array(as.POSIXct(x), type = timestamp())
a_a
#> ChunkedArray
#> <timestamp[s]>
#> [
#>   [
#>     1900-01-01 00:00:00
#>   ]
#> ]

out <- as.vector(a_a)

as.POSIXct(x)
#> [1] "1900-01-01 UTC"
unclass(as.POSIXct(x))
#> [1] -2208988800
#> attr(,"tzone")
#> [1] ""
out
#> [1] "1900-01-01 UTC"
unclass(out)
#> [1] -2208988800

Sys.setenv(TZ = "Europe/Paris")

as.POSIXct(x)
#> [1] "1900-01-01 PMT"
unclass(as.POSIXct(x))
#> [1] -2208989361
#> attr(,"tzone")
#> [1] ""
out
#> [1] "1900-01-01 00:09:21 PMT"
unclass(out)
#> [1] -2208988800
```

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by eitsupi** [comment] 2024-03-01 15:19
I think we should do something like this:

``` r
Sys.setenv(TZ = "UTC")
x = "1900-01-01"
s = polars::as_polars_series(x)$str$strptime(pl$Datetime(), "%F")

s
#> polars Series: shape: (1,)
#> Series: '' [datetime[μs]]
#> [
#>  1900-01-01 00:00:00
#> ]

out = s$dt$replace_time_zone(Sys.timezone()) |>
  as.vector()
attr(out, "tzone") <- NULL
out
#> [1] "1900-01-01 UTC"

Sys.setenv(TZ = "Europe/Paris")

out = s$dt$replace_time_zone(Sys.timezone()) |>
  as.vector()
attr(out, "tzone") <- NULL
out
#> [1] "1900-01-01 PMT"
```

<sup>Created on 2024-03-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by etiennebacher** [comment] 2024-03-01 17:07
I'm in no position to say if this behavior is correct or not, but I think we should be consistent and not decide just for `polars`. I suggest waiting for more information on `arrow`'s side so that we can deal with that as they do. 

In the meantime, we could explicitly set the timezone to "UTC" in the tests so that they work for me (and other people in the Paris timezone). What do you think about that?

(In retrospect we were quite lucky to catch this in the tests as it was "fixed" 100+ years ago)

**Comment by eitsupi** [comment] 2024-03-02 05:26
I noticed that the arrow package provides little functionality for creating time types without a time zone.
(There was a bit of discussion about not being able to provide sufficient functionality without integration with the clock package, but it has not happened.)

Input from R is affected by the time zone of the session.

``` r
Sys.setenv(TZ = "UTC")

data.frame(x = as.POSIXct("1900-01-01")) |> arrow::as_arrow_table() |> _$x
#> ChunkedArray
#> <timestamp[us]>
#> [
#>   [
#>     1900-01-01 00:00:00.000000
#>   ]
#> ]

Sys.setenv(TZ = "Europe/Paris")

data.frame(x = as.POSIXct("1900-01-01")) |> arrow::as_arrow_table() |> _$x
#> ChunkedArray
#> <timestamp[us]>
#> [
#>   [
#>     1899-12-31 23:50:39.000000
#>   ]
#> ]
```

<sup>Created on 2024-03-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In an arrow dplyr query, `as.POSIXct()` cannot be used and the function from lubridate is likely to be used instead.
https://arrow.apache.org/docs/r/reference/acero.html#lubridate

And unlike `as.POSIXct()`, `lubridate::as_datetime()` gives time zone information before it is converted to the Arrow type.

``` r
Sys.setenv(TZ = "UTC")

data.frame(x = lubridate::as_datetime("1900-01-01")) |> arrow::as_arrow_table() |> _$x
#> ChunkedArray
#> <timestamp[us, tz=UTC]>
#> [
#>   [
#>     1900-01-01 00:00:00.000000
#>   ]
#> ]

Sys.setenv(TZ = "Europe/Paris")

data.frame(x = lubridate::as_datetime("1900-01-01")) |> arrow::as_arrow_table() |> _$x
#> ChunkedArray
#> <timestamp[us, tz=UTC]>
#> [
#>   [
#>     1900-01-01 00:00:00.000000
#>   ]
#> ]
```

<sup>Created on 2024-03-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

For this reason, few people have paid attention to the behavior of the arrow package until now.

(Also, like myself, I believe that users who have been hurt by time zone conversions in the past are more likely to set their system time zone to UTC......)

**Comment by eitsupi** [comment] 2024-03-02 08:06
Interestingly, nanoarrow gives time zone information when converting from POSIXct and sets the UTC time zone when converting from timestamp type without time zone to POSIXct.

In other words, it is not compatible with the arrow package, but it is a reasonable behavior.

**Closed** 2024-03-02 16:45 UTC
Labels: bug
