### ISSUE TITLE
dev docs fails

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#171] opened 2023-04-24 07:55 UTC
Dev docs seems not to work. These are mainly used for fast feedback while coding.

example
```R
rextendr::document()
?LazyFrame_describe_plan

ℹ Rendering development documentation for "LazyFrame_describe_plan"
Error in .get_package_metadata(pkgdir) : 
  Files 'DESCRIPTION' and 'DESCRIPTION.in' are missing.
 
```

I have traced the error with `{browser();?LazyFrame_describe_plan}` to `pkgload::dev_help()`, but I don't know why it happens.

**Comment by etiennebacher** [comment] 2023-04-24 08:59
I had the same issue, maybe it's fixed in the last version of RStudio (I don't have the last one): https://github.com/rstudio/rstudio/issues/12945

**Comment by eitsupi** [comment] 2023-04-24 10:54
Was the documentation generated by `devtools::document`?
(I think it acted like it was skipping documentation generation, but I could be mistaken)

**Comment by sorhawell** [comment] 2023-04-24 22:24
It is via rextendr::document which probably calls devtools::document(). The help pages are then lazily rendered for every ?function_name call.

**Comment by etiennebacher** [comment] 2023-04-26 07:17
The issue is either due to RStudio or to `pkgload` (cf the issue linked above), I think this can be closed since there's nothing we can do

**Closed by etiennebacher** 2023-04-26 07:17 UTC
