### ISSUE TITLE
Is it possible to use $map_elements on `struct` columns?

### ISSUE THREAD

**Issue by ToddMCr** [pola-rs/r-polars#1106] opened 2024-05-25 22:47 UTC
I am trying to translate this python code

```py
import polars as pl
import numpy as np
from numpy.random import normal

df = pl.DataFrame({
    "group": ["control", "treatment"],
    "alpha": [1,1], 
    "beta": [0, 1],
    "sigma": [1,1]
})

df = df.join(pl.DataFrame({"time": np.arange(0, 10+1)}),
             how="cross")

df = df.with_columns(
    pl.struct(["alpha", "beta", "sigma", "time"]).map_elements(
        function=lambda t: (
        pl.Series(name="y",
                  values=normal(t['alpha'] + t['beta']*t['time'], 
                                t['sigma'], 
                                3))
        ),
        return_dtype=pl.List(pl.Float64))
    .alias("y")
)
```

To R:
```r
library(polars)

df = pl$DataFrame(group = c("control", "treatment"),
                  alpha = c(1, 1),
                  beta = c(0, 1),
                  sigma = c(1,1))

df = df$join(pl$DataFrame(time = 0:10), 
             how = "cross")

df$with_columns(
    pl$struct(c("alpha","beta","sigma","time"))$map_elements(\(t) {
        # generate data
        t
    })
)
```

But I am getting the following error even when I return the same element `t`:
```
[src/series.rs:444:17] x = Struct(
    [
        Field {
            name: "alpha",
            dtype: Float64,
        },
    ],
)
thread '<unnamed>' panicked at src/series.rs:445:17:
not yet implemented: this input type is not implemented
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/series.rs:91:1:
explicit panic
Error in .pr$Series$map_elements(self, fun, datatype, strict_return_type,  : 
  user function panicked: map_elements
Error: Execution halted with the following contexts
   0: In R: in $with_columns()
   0: During function call [df$with_columns(pl$struct("alpha")$map_elements(function(t) {
          t
      }))]
   1: user function raised an error: EvalError(lang!(function (s) {    s$map_elements(f, return_type, strict_return_type, allow_fail_eval)}, ExternalPtr.set_class(["RPolarsSeries"])) 
```
I assume the `not yet implemented: this input type is not implemented` means that this isn't supported yet, but I just wanted to check if there was a work around or if iterating over struct columns is being worked on?

**Comment by eitsupi** [comment] 2024-05-26 03:11
Thanks for sharing your examples.

But I think this issue is a duplicate of #993

**Closed by eitsupi** 2024-05-26 03:11 UTC

**Comment by ToddMCr** [comment] 2024-05-26 03:16
Ah sorry somehow I didn't see that issue, thank you!
