### ISSUE TITLE
prefix + `%` crashes R

### ISSUE THREAD

**Issue by sorhawell** [pola-rs/r-polars#258] opened 2023-06-23 13:32 UTC
passing `%` as char to prefix will crash the rsession

```R
library(polars)
df = pl$DataFrame(mtcars)
df3 = do.call(df$select,list(pl$all()$quantile(.5)$prefix("hi%")))
print(df3)
```

**Comment by sorhawell** [comment] 2023-06-24 21:53
maybe somewhere between rust and extendr the `%` is cursed 

add debug print to prefix
```rust
    fn prefix(&self, prefix: Robj) -> RResult<Self> {
        let s = robj_to!(String, prefix)?;
        rprintln!("bytes{:?} \n", s.as_bytes());
        s.chars().into_iter().for_each(|c| {
            //hey
            rprintln!(" c[{:?}-{}]", c, c);
        });
        Ok(self.0.clone().prefix(s.as_str()).into())
    }

```

it seems rust dbg fmt cannot display % properly however other exotic chars works fine

```R
> pl$col()$prefix("%")
bytes[37] 

 c['%]
$ok
polars Expr: RENAME_ALIAS col("")

$err
NULL

attr(,"class")
[1] "extendr_result"
> pl$col()$prefix("◊")
bytes[226, 151, 138] 

 c['◊'-◊]
$ok
polars Expr: RENAME_ALIAS col("")

$err
NULL

attr(,"class")
[1] "extendr_result"
```

**Comment by sorhawell** [comment] 2023-06-26 10:09
fixed when #252  merges

**Comment by sorhawell** [comment] 2023-06-27 10:12
the final fix is found [here in extendr](https://github.com/extendr/extendr/pull/566)

**Comment by etiennebacher** [comment] 2023-06-30 11:29
All linked PRs are merged and the behavior now looks correct so I'm closing this:
```r
> library(polars)
>   df = pl$DataFrame(mtcars)
>   df3 = do.call(df$select,list(pl$all()$quantile(.5)$prefix("hi%")))
>   df3
shape: (1, 11)
┌────────┬────────┬─────────┬───────┬───┬───────┬───────┬─────────┬─────────┐
│ hi%mpg ┆ hi%cyl ┆ hi%disp ┆ hi%hp ┆ … ┆ hi%vs ┆ hi%am ┆ hi%gear ┆ hi%carb │
│ ---    ┆ ---    ┆ ---     ┆ ---   ┆   ┆ ---   ┆ ---   ┆ ---     ┆ ---     │
│ f64    ┆ f64    ┆ f64     ┆ f64   ┆   ┆ f64   ┆ f64   ┆ f64     ┆ f64     │
╞════════╪════════╪═════════╪═══════╪═══╪═══════╪═══════╪═════════╪═════════╡
│ 19.2   ┆ 6.0    ┆ 225.0   ┆ 123.0 ┆ … ┆ 0.0   ┆ 0.0   ┆ 4.0     ┆ 2.0     │
└────────┴────────┴─────────┴───────┴───┴───────┴───────┴─────────┴─────────┘
```

**Comment by eitsupi** [comment] 2023-06-30 13:12
Perhaps additional tests should be added?
(I mean, this comes from extendr, so I'm worried about regression due to extendr updates)

**Comment by etiennebacher** [comment] 2023-06-30 19:24
Yes we should add a test for this

**Comment by eitsupi** [comment] 2023-07-01 04:16
@etiennebacher How about #284?

**Comment by etiennebacher** [comment] 2023-07-01 06:04
Oh I didn't see this PR

**Closed by etiennebacher** 2023-07-01 06:04 UTC
Labels: bug
